---
image: docker:git

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk update && apk add --no-cache docker
    python3-dev py3-pip docker gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - docker info
  - python3 --version
  - pip3 install -r requirements.txt
  - ansible --version
  - molecule --version

centos7:
  stage: test
  script:
    - molecule test --scenario-name centos7

fedora:
  stage: test
  script:
    - molecule test --scenario-name fedora

debian9:
  stage: test
  script:
    - molecule test --scenario-name fedora

ubuntu1804:
  stage: test
  script:
    - molecule test --scenario-name ubuntu1804
