---
# tasks file for ansible-role-init

- name: Install python support for Ansible
  raw: yum install -y python
  tags: init

- action: setup
  tags: init

- name: Make sure essential software is installed
  yum:
    name:
      - python
      - sudo
    state: 'latest'
  tags: init

- name: Create '{{ ssh_user }}' account
  user:
    name: '{{ ssh_user }}'
    state: 'present'
    shell: '/bin/bash'
  tags: init

- name: Get current workdir
  tags:
    - users
    - pubkeys
  set_fact:
    pwd: "{{ lookup('env', 'PWD') }}"

- name: Create path to keys (step1)
  tags:
    - users
    - pubkeys
  set_fact: 
    interim_string: "{% for item in ssh_keys %}{{pwd}}{{ssh_keys_path}}/{{item}} {% endfor %}"

- name: Create path to keys (step2)
  tags:
    - users
    - pubkeys
  set_fact: 
    ssh_keys_path: "{{ interim_string.split() }}"

- name: Install ssh public key(s)
  authorized_key:
    user: '{{ ssh_user }}'
    key: '{{ item }}'
    state: 'present'
  with_file: '{{ ssh_keys_path }}'
  failed_when: (ssh_keys is undefined or (ssh_keys is defined and not ssh_keys))
  tags: 
    - init
    - ssh

- name: Configure '{{ ssh_user }}' user privileged access by sudo
  lineinfile:
    dest: '/etc/sudoers.d/ansible'
    state: 'present'
    create: True
    regexp: '^%{{ ssh_user }}'
    line: '%{{ ssh_user }} ALL=(ALL) NOPASSWD: SETENV: ALL'
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: 'visudo -cf %s'
  tags: init
