---
# handlers file for elcomtik.init
- name: Restart sshd service
  ansible.builtin.service:
    name: "sshd"
    state: "restarted"
  become: True
  async: 5
  poll: 1

- name: Reload firewalld service
  ansible.builtin.service:
    name: "firewalld"
    state: "reloaded"
  become: true
