---
- hosts: all
  tasks:
    - name: Ensure SSHD is installed
      package:
        name: openssh-server
      become: true
    
    - name: Ensure SSHD is started
      service:
        name: sshd
        state: started
      become: true
